### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bkzutr90** [donno2048/imtost#18]
info:     [session] Initializing browser wss...
Chrome not found, using chromium

          A plugin listed 'puppeteer-extra-plugin-stealth/evasions/defaultArgs' as dependency,
          which is currently missing. Please install it:

          yarn add puppeteer-extra-plugin-stealth

          Note: You don't need to require the plugin yourself,
          unless you want to modify it's default settings.

info:     [session] Error no open browser....
(node:77294) UnhandledPromiseRejectionWarning: Error no open browser....
(Use `node --trace-warnings ...` to show where the warning was created)
(node:77294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:77294) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by donno2048** [comment]
Could you send any reproduction steps? I can't reproduce the issue...

**Comment by donno2048** [comment]
No response, closing as stale, feel free to reopen

**Comment by bkzutr90** [comment]
I following ur steps on readme.md

**Comment by donno2048** [comment]
Why do you have a `yarn` error?
